### ISSUE TITLE
Support latest buildtools/CXX17

### ISSUE THREAD

**Issue by bbernhar** [webmachinelearning/webnn-native#196]
I regularly roll WebNN into GPGMM in my CI [1] and also keep the DEPS synced to Chromium/Dawn to stay build compatible. However, I noticed in my most recent DEPS sync [2] the latest buildtools version breaks `third_party/webnn`. I think the latest DEPS will require WebNN to support CXX17 at some point so I propose we use this issue to capture the work.

@huningxin @fujunwei 

[1] https://github.com/intel/GPGMM/actions/workflows/win_webnn_rel.yaml
[2] https://github.com/intel/GPGMM/pull/117/files#diff-4cc955bcf0b472353786cc8d8b7d346fb432c091bed099de884885e938392814

**Comment by huningxin** [comment]
I think webnn-native should also sync to Chromium/Dawn. @fujunwei , given your recent Dawn refactory, I suppose it would be easier to do so, correct?

**Comment by bbernhar** [comment]
Yea, too bad we don't have a auto-roller workflow/bot [1] =(

[1] https://chromium-review.googlesource.com/q/owner:chromium-autoroll%2540skia-public.iam.gserviceaccount.com

**Comment by fujunwei** [comment]
> I think webnn-native should also sync to Chromium/Dawn. @fujunwei , given your recent Dawn refactory, I suppose it would be easier to do so, correct?

The [forked branch](https://github.com/fujunwei/webnn-native-1) implement webnn in Dawn directory structure as sub-folder, DML backend can work now, but the approach still is discussing, so i don't merge to main branch.

**Comment by bbernhar** [comment]
@fujunwei shouldn't we keep this issue open until we roll DEPS? I am (still) unable to build `third_party\WebNN` due to compiler-errors.

**Comment by bbernhar** [comment]
Re-opening b/c HEAD or e83ae3e196c276be8e54f5262690fa944d04790d still fails to build under `.\third_party` and DEPS. Digging deeper, the shared macro `DAWN_NO_DISCARD` definition is not available to WebNN.
