### ISSUE TITLE
[DML] respect the power preference for adaptor selection

### ISSUE THREAD

**Issue by huningxin** [webmachinelearning/webnn-native#200]
The DML backend should respect the power preference and select the appropriate adaptor available on the device.

It could use [EnumAdapterByGpuPreference](https://docs.microsoft.com/en-us/windows/win32/api/dxgi1_6/nf-dxgi1_6-idxgifactory6-enumadapterbygpupreference) API and set corresponding [DXGI_GPU_PREFERENCE](https://docs.microsoft.com/en-us/windows/win32/api/dxgi1_6/ne-dxgi1_6-dxgi_gpu_preference):

```c++
typedef enum DXGI_GPU_PREFERENCE {
  DXGI_GPU_PREFERENCE_UNSPECIFIED = 0,
  DXGI_GPU_PREFERENCE_MINIMUM_POWER,
  DXGI_GPU_PREFERENCE_HIGH_PERFORMANCE
} ;
```

**Comment by mingmingtasd** [comment]
Fixed by PR #204  #203
