### ISSUE TITLE
Typo issue for 'lower-power' in README files.

### ISSUE THREAD

**Issue by BruceDai** [webmachinelearning/webnn-native#213]
@mingmingtasd Please modify typo issue `lower-power` to [`low-power`](https://github.com/webmachinelearning/webnn-native/blob/main/examples/SampleUtils.cpp#L171), thanks.

**Comment by BruceDai** [comment]
Please also update this cpp `std::cout ` code on https://github.com/webmachinelearning/webnn-native/blob/main/examples/SampleUtils.cpp#L425.

**Comment by mingmingtasd** [comment]
Fix by [PR](https://github.com/webmachinelearning/webnn-native/pull/214), close it.
