### ISSUE TITLE
Auto rolling DEPS

### ISSUE THREAD

**Issue by bbernhar** [webmachinelearning/webnn-native#248]
It's a bit annoying to manually roll each and every entry in [DEPS](https://github.com/webmachinelearning/webnn-native/blob/main/DEPS), multiplied by the number of downstream repos within each. 

Google/Dawn created a [auto-roller bot](https://dawn.googlesource.com/dawn/+/71b5ea803d01f3e4e6820f2eb21056f3c8465443) that keeps them in sync and "ever green" (top-of-tree).

Maybe we could come up with a shared GitHub workflow that runs "roll-deps" periodically? Sounds like a good intern project!

@huningxin @fujunwei

**Comment by fujunwei** [comment]
Sounds good.
cc @BruceDai @ibelem

**Comment by BruceDai** [comment]
Thanks @bbernhar for your kindly suggestion. There're other projects also need to roll DEPS. I will investigate how to enable auto rolling DEPS.

**Comment by bbernhar** [comment]
Thanks @BruceDai!

**Comment by bbernhar** [comment]
@BruceDai I have this partially working over in GPGMM. I wrote a GitHub workflow that automatically runs `roll-deps` per DEPS then creates these as separate PRs. With auto-merge enabled, it could "auto roll" into main. PTAL.

https://github.com/intel/GPGMM/actions/workflows/win_auto_roll.yaml

**Comment by BruceDai** [comment]
Thanks much @bbernhar. We will refer to your **win_auto_roll.yaml** to add Auto roll CI for this repo firstly.

**Comment by bbernhar** [comment]
@BruceDai Any update here? I've been using the auto roller for a couple weeks now and it works great!

**Comment by BruceDai** [comment]
Thanks @bbernhar. Last I added [my auto roll CI](https://github.com/BruceDai/webnn-native/commit/87f9999779f588a9dabd4dc8b94501020b654216) into my forked repo,  while there're failures of 'Create Pull Request', we're investing whether it's with the token
```yml
token: ${{ secrets.REPO_ACCESS_TOKEN }}
```

Any suggestion, thanks.

**Comment by bbernhar** [comment]
@BruceDai Sounds like it. You'll need to create a PAT named `REPO_ACCESS_TOKEN` with appropriate [access](https://github.com/peter-evans/create-pull-request).

**Comment by bbernhar** [comment]
@BruceDai?

**Comment by BruceDai** [comment]
Yes, I created my own PAT for [my forked webnn-native](https://github.com/BruceDai/webnn-native), and enabled permissions for it.  Now errors like:

![image](https://user-images.githubusercontent.com/1531742/182996745-92706ccb-d695-4e5d-86be-07ab7318f7e0.png)

I enabled following Workflow permissions
![image](https://user-images.githubusercontent.com/1531742/182997441-9594a80c-78a6-43a4-a1f6-6087d43826d0.png)

My git settings
![image](https://user-images.githubusercontent.com/1531742/182996848-1811ca05-1dbc-4016-9cd8-3491be57bb92.png)

PTAL, thanks.

**Comment by bbernhar** [comment]
@BruceDai You can't use your PAT on a forked repository, the PAT will only allow read access (but the workflow requires write-access). I think you need to commit the workflow directly to `webmachinelearning/webnn-native` to get it to work.

Also, you have an old version of the GPGMM Auto Roller. The new version has been fixed to work with multiple rolls per PR.

Let me know how it goes.

**Comment by BruceDai** [comment]
PR #290 was submitted, @bbernhar PTAL, thanks.
