### ISSUE TITLE
[Python Generator] Initialize OperandBase* and OperatorBase to nullptr

### ISSUE THREAD

**Issue by mingmingtasd** [webmachinelearning/webnn-native#61]
Now OperandBase*(or operatorBase*) in operand options struct hasn't been initialized, as below:
```
   struct ClampOptions {
        OperandBase* minValue;
        OperandBase* maxValue;
    };
```
We may need initialize them to nullptr.

**Comment by mingmingtasd** [comment]
Some other ones like struct MLContextOptions{}, struct MLConv2dOptions{} in webnn.h may also need default values.

**Comment by huningxin** [comment]
The webnn_cpp.h has default values. Are you fine with that?

**Comment by huningxin** [comment]
BTW, for `ClampOptions` in webnn_cpp.h:
```c++
struct ClampOptions {
     Operand minValue;
     Operand maxValue;
};
```
The default `Operand` contains nullptr, I suppose it should meet the requirement.

**Comment by mingmingtasd** [comment]
I mean C struct like:
struc [ClampOptions](https://github.com/webmachinelearning/webnn-native/blob/main/src/webnn_native/ops/Clamp.h#L41) {
        OperandBase* minValue;
        OperandBase* maxValue;
    };
has no default values like `OperandBase* minValue = nullptr`, am I right? Thanks! @huningxin @fujunwei

**Comment by fujunwei** [comment]
The Object need to support  `optional = true` in webnn.json so that the c struct can have default nullptr after generating by python. so the assign manually can be removed. I can send a PR to support it.
https://github.com/webmachinelearning/webnn-native/blob/main/src/webnn_native/ops/Clamp.h#L30
```
ClampBase(ClampOptions const* options) {
            if (options != nullptr) {
                mOptions = *options;
            } else {
                mOptions.minValue = nullptr;
                mOptions.maxValue = nullptr;
            }
        }
```

```
struc ClampOptions {
OperandBase* minValue = nullptr;
OperandBase* maxValue = nullptr;
};
```

**Comment by huningxin** [comment]
webnn.h is for C language which doesn't support default values for `struct`.

**Comment by fujunwei** [comment]
> webnn.h is for C language which doesn't support default values for `struct`.

Yes, We can't assign default values in `webnn.h` but `webnn_structs_autogen.h `that is C++ struct. The C struct will convert to C++ struct.

For example, clamp option in webnn.h
```
typedef struct MLClampOptions {
    MLOperand minValue;
    MLOperand maxValue;
} MLClampOptions;
```
clamp option in webnn_structs_autogen.h

 ```
struct ClampOptions {
        OperandBase* minValue;
        OperandBase* maxValue;
    };
```
convert struct in ProcTable.cpp to call c++ API.

```
MLOperand NativeGraphBuilderClamp(MLGraphBuilder cSelf, MLOperand input, MLClampOptions const * options) {
            auto self = reinterpret_cast<GraphBuilderBase*>(cSelf);

            auto input_ = reinterpret_cast<OperandBase* >(input);
            auto options_ = reinterpret_cast<ClampOptions const * >(options);
            auto result =            self->Clamp(input_, options_);
            return reinterpret_cast<MLOperand>(result);
        }
```

**Comment by huningxin** [comment]
> but `webnn_structs_autogen.h `that is C++ struct. The C struct will convert to C++ struct.

Thanks for the details. This makes sense. I'll fix that.
