### ISSUE TITLE
[OV] conv2d and pool2d tests crash for debug build

### ISSUE THREAD

**Issue by huningxin** [webmachinelearning/webnn-native#67]
Build debug version and run conv2d or pool2d tests:
```shell
$ out/Debug/webnn_end2end_tests --gtest_filter=*Conv2dTests*
Note: Google Test filter = *Conv2dTests*
[==========] Running 66 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 66 tests from Conv2dTests
[ RUN      ] Conv2dTests.Conv2dWithPaddingDefault
webnn_end2end_tests: /home/nhu/code/webnn-native/third_party/openvino/ienn/src/ie_model.cpp:414: ie_operand_t* InferenceEngine::Model::AddConv2d(ie_operand_t*, ie_operand_t*, ie_conv2d_options_t*): Assertion `0' failed.
Aborted (core dumped)
```

The crash is caused by setting autoPad as explicit for conv2d and pool2d. The [code](https://github.com/webmachinelearning/webnn-native/blob/main/third_party/openvino/ienn/src/ie_model.cpp#L412) of conv2d to handle explicit case should break instead of passing through to default case. Same to pool2d.

**Comment by mingmingtasd** [comment]
I checked that this issue has been fixed, close it.
